### ISSUE TITLE
In snake.py, player moving back ends the game.

### ISSUE THREAD

**Issue by Typeaway14** [acmpesuecc/Bustle-Slot-Booking#12]
If the player happens to move in the direction of the rest of his body, the game ends. It would be better if it ignored that particular input instead of ending the game.

**Comment by MaNameEJeff** [comment]
Hey can I be added to this issue :)

**Comment by mukunddeepak** [comment]
go ahead! Its open access time! Make a PR!

**Comment by mukunddeepak** [comment]
You can do it without being assigned till 8 PM
