### ISSUE TITLE
Running Sudoku solver using the spacebar terminates the program with an error

### ISSUE THREAD

**Issue by Typeaway14** [acmpesuecc/Bustle-Slot-Booking#28]
Playing the game normally doesnt cause issues. However, if the user presses the spacebar to solve the board and then closes the program, it terminates the program with an error.

**Comment by MaNameEJeff** [comment]
Hey, can I be added to this :)

**Comment by mukunddeepak** [comment]
Sure All the best!

**Comment by mukunddeepak** [comment]
!bounty 50

**Comment by Typeaway14** [comment]
!bounty 50

**Comment by gorumeg** [comment]
Hi, can I please be added to this?

**Comment by mukunddeepak** [comment]
!bounty 50

**Comment by Typeaway14** [comment]
Hi @gorumeg, this issue has already been solved by #35.
