### ISSUE TITLE
Clear screen for Linux

### ISSUE THREAD

**Issue by Typeaway14** [acmpesuecc/Bustle-Slot-Booking#33]
The current implementation for clearing the screen works only for windows. It's a lambda function that runs `cls` on the cmd terminal.
This doesnt work on Linux. Find a way to fix this and make the code compatible with Linux and Windows both!

**Comment by MaNameEJeff** [comment]
Hey can I be added to this issue :)

**Comment by n1haldev** [comment]
Hey can I be added to this issue
-n1haldev

**Comment by mukunddeepak** [comment]
Go ahead!

**Comment by Typeaway14** [comment]
hey @surajkadapa it's open access time! Go ahead and make a PR
