### ISSUE TITLE
Add a new game to the games list!

### ISSUE THREAD

**Issue by Typeaway14** [acmpesuecc/Bustle-Slot-Booking#34]
Add a fully functional game for the games list and make it compatible with the voucher system! It can be any game at all!

**Comment by sean-18** [comment]
@Typeaway14 can i assigned this issue

**Comment by sean-18** [comment]
can i be assigned this issue 
-Sean Sougaijam

**Comment by Typeaway14** [comment]
Go ahead @sean-18 !

**Comment by itsjiyapatel** [comment]
can i be assigned this issue
-jiya patel

**Comment by Vaarun-Kamath** [comment]
can i have this?

**Comment by SahilPrabhu** [comment]
can i be assigned this issue?

**Comment by n1haldev** [comment]
Can I be assigned to this issue?

**Comment by Typeaway14** [comment]
It's open access for 3 more minutes. Go ahead guys!

**Comment by architanand95** [comment]
can i be assigned this

**Comment by Typeaway14** [comment]
Go ahead @oshinsaraf! You have been assigned! You now have 45 minutes before your access is handed over to someone else!

**Comment by Typeaway14** [comment]
Apologies for closing the issue :P

**Comment by brindach** [comment]
kindly assign the issue

**Comment by pranjalala** [comment]
can i be assigned to the issue, PRN: PES2202200363

**Comment by Typeaway14** [comment]
@oshinsaraf Time has been extended for you due to a small issue in your PR. Fix that within the next 20 minutes and we'll accept the PR. Else we will have to hand it over to someone else :P

**Comment by brindach** [comment]
can I be assigned the issue,PRN:PES2202200453

**Comment by KunalMaverick** [comment]
Is this assigned to someone?
or if not
can i be assigned to this?

**Comment by Typeaway14** [comment]
We're waiting on @oshinsaraf to give us an update. If we do not get one we'll assign it to @brindach (cant tag them for some reason :?)

**Comment by GSL006** [comment]
@Typeaway14  can I be assigned to the issue?

**Comment by GSL006** [comment]
PRN:PES2202200752

**Comment by Typeaway14** [comment]
@oshinsaraf No updates from your side, we'll have to assign this issue to brindach

**Comment by mukunddeepak** [comment]
@KunalMaverick is being assigned this issue!

**Comment by druva344** [comment]
NOW CAN I BE ASSIGNED THIS ISSUE??

**Comment by tnayagarwal** [comment]
@Typeaway14 @mukunddeepak can i get assigned for this

**Comment by mukunddeepak** [comment]
> NOW CAN I BE ASSIGNED THIS ISSUE??

Please Settle Down. The Issues are being assigned in FCFS order. Also it is unassigned when blocking time is over and there is no progress.

**Comment by ad1tya24** [comment]
I would like to work on this

**Comment by mukunddeepak** [comment]
Ok no update from @KunalMaverick either

**Comment by nik2203** [comment]
hi can i be assigned to this issue

**Comment by mukunddeepak** [comment]
@GSL006 Block time is 15 mins JUTPUTJUTPUT

**Comment by mukunddeepak** [comment]
Let's make it more interesting. Let's open it to the others to add more games and it should be added in bustle.py and game_files also. Code and all files should be well named and well structured.

**Comment by mukunddeepak** [comment]
First PR gets the points. Please make sure to get all above factors to get all the points

**Comment by mukunddeepak** [comment]
I'm accepting one more PR. But points will be reducted.

**Comment by siddarthpai** [comment]
hey can i work on this
